### ISSUE TITLE
Maximise not working?

### ISSUE THREAD

**Issue by gregroyal** [SillyFreak/svelte-golden-layout#2]
Looking at the example page, looks like icons aren't rendering and when you maximize the content, the component doesnt render
https://sillyfreak.github.io/svelte-golden-layout/

**Comment by ensko** [comment]
Hi gregroyal, thanks for the bug report!

Re icons: there were wrong paths in the themes CSS I embedded in the library; I fixed that once and for all by putting these icons into the css files as base64, as it was already the case with some of the default GoldenLayout themes.

Re component rendering: this was a z-index problem; I seem to have not registered the relevant event handler

There also was another issue: while one tabset is maximized, other tabsets would overflow; this problem is also present in the [vue3 integration linked by the GoldenLayout docs](https://github.com/chyj4747/vue3-golden-layout-virtualcomponent), although their example fills the screen, so the overflow is not visible anyway. This should now be fixed.

The demo and NPM package (0.1.1) have been updated, would you mind confirming if this fixed the issues for you?

**Comment by gregroyal** [comment]
yes this fix the issue for me! sorry I forgot about this heh. Updated worked! appreciate it
